name = "Jade ğŸ”"
filename = "Jade-1.18.2-5.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3761/542/Jade-1.18.2-5.1.0.jar"
hash-format = "sha1"
hash = "559a07d2f55b6c56fcc7416e7fb901f182a3eb41"

[update]
[update.curseforge]
file-id = 3761542
project-id = 324717
