name = "Jade ğŸ”"
filename = "Jade-1.18.2-5.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/449/Jade-1.18.2-5.0.1.jar"
hash-format = "sha1"
hash = "744aba3401d6b8a1bcdad275ca646e05796c047c"

[update]
[update.curseforge]
file-id = 3681449
project-id = 324717
